name: Run coverity static analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run coverity static analysis
      env:
        PLATFORM: linux
        BITS: 64
        HOST: x86_64
        CHECK_RULE: coverage
        GCOV: 1
        PKG_RULE: gzip
        PYPI: yes
        COVERITY_SCAN_PROJECT_NAME: ${{ github.repository }}
        COVERITY_SCAN_BRANCH_PATTERN: master
        COVERITY_SCAN_NOTIFICATION_EMAIL: "cse-ci-notifications@analog.com"
        COVERITY_SCAN_BUILD_COMMAND_PREPEND: "mkdir build && cd build && cmake -DWITH_EXAMPLES=ON .."
        COVERITY_SCAN_BUILD_COMMAND: make
      run: echo "Nothing to do in GH actions (yet)?"
